name: Django tests

on:
    push:
        branches:
            - main

    pull_request:
        branches:
            - main

# on:
#    schedule:
#        - corn: '*/15 * * * *'

jobs:
    builds:

        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2
        - name: setup python
          uses: actions/setup-python@v2
          with:
            python-version: 3.11
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        - name: Lint with flake8
          run: |
            pip install flake8
            flake8
        - name: Coverage report
          run: |
            pip install coverage
            coverage run manage.py test
            coverage report
        - name: Django Testing
          run: |
            python manage.py test